# Generated by Django 3.0.3 on 2020-02-13 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='communities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='defibModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modelNr', models.IntegerField()),
                ('automatic', models.BooleanField(default=False)),
                ('guided', models.BooleanField(default=False)),
                ('compression', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('defib', 'Defibrillator'), ('sos', 'SOS Telephone')], default='defib', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalCode', models.IntegerField()),
                ('street', models.CharField(max_length=150)),
                ('language', models.CharField(choices=[('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('en', 'English')], default='de', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('availability', models.CharField(blank=True, max_length=300, null=True)),
                ('pc', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
                ('location_descr', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=300)),
                ('responsible', models.CharField(max_length=100)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.communities')),
                ('type', models.ForeignKey(default='defib', on_delete=django.db.models.deletion.CASCADE, to='mainApp.type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='communityinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalCode', models.IntegerField()),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.communities')),
            ],
        ),
        migrations.CreateModel(
            name='attributesDefib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.items')),
                ('model', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.defibModels')),
            ],
        ),
    ]
