# Generated by Django 3.0.3 on 2020-02-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalCode', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='defibModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modelNr', models.IntegerField()),
                ('automatic', models.BooleanField(default=False)),
                ('guided', models.BooleanField(default=False)),
                ('compression', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('defib', 'Defibrillator'), ('sos', 'SOS Telephone')], default='defib', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='mainApp.community')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='mainApp.type')),
            ],
        ),
        migrations.CreateModel(
            name='attributesDefib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mainApp.items')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defibModels', to='mainApp.defibModels')),
            ],
        ),
    ]
