# Generated by Django 2.2.5 on 2020-02-13 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200213_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemss', to=settings.AUTH_USER_MODEL),
        ),
    ]
